#include <iostream>
#include <stdlib.h>
#include <tools.cpp>
#include <memory.cpp>
#include <dataHash.cpp>
#include <functionHash.cpp>
#include <locationStack.cpp>
#include <instruction.cpp>
#include <stdSpecTemplate.cpp>
#include <helpers.cpp>